/**
 * Inngest function: onboard a new member who joined #tamtam-team.
 *
 * Sequence:
 *   step.sleep 30s — feels less robotic than instant
 *   Rama welcomes (in her voice via speakAs)
 *   step.sleep 45s
 *   Kofi chimes in
 *   step.sleep 60s
 *   Awa chimes in
 *
 * Each message is generated by Claude using that agent's system
 * prompt — never hardcoded. We pass the new member's user id so
 * each agent can address them with `<@USERID>` if they choose.
 */

import { inngest } from "@/lib/inngest";
import { speakAs } from "@/lib/team-voice";
import { logAgentAction } from "@/lib/supabase";

export const memberOnboarding = inngest.createFunction(
  {
    id: "member-onboarding",
    name: "Welcome new #tamtam-team member",
    // Don't double-welcome if Slack delivers the same join twice.
    concurrency: { limit: 1, key: "event.data.user_id" },
  },
  { event: "tamtam/team.member-joined" },
  async ({ event, step }) => {
    const { user_id, channel } = event.data;

    await step.run("log-arrival", async () =>
      logAgentAction({
        agent: "coo",
        action: "team.member_joined",
        metadata: { user_id, channel },
        status: "started",
      }),
    );

    // 30-second pause so the welcome doesn't feel automated.
    await step.sleep("welcome-pause", "30s");

    const ramaTurn = await step.run("rama-welcomes", async () =>
      speakAs({
        agent: "coo",
        channel,
        brief:
          `A new person just joined #tamtam-team — their Slack user ` +
          `id is <@${user_id}>. Welcome them as Rama. Introduce ` +
          `yourself in one line, then introduce Awa (Social) and ` +
          `Kofi (Growth) in one line each, and mention Georges as ` +
          `the founder. Make them feel like they walked into a real ` +
          `Dakar office, not a chatbot demo. Five lines max. Use ` +
          `<@${user_id}> at the start so they get notified. No bullet ` +
          `lists.`,
        source: "onboarding.rama",
        maxTokens: 350,
      }),
    );

    await step.sleep("kofi-pause", "45s");

    const kofiTurn = await step.run("kofi-chimes", async () =>
      speakAs({
        agent: "growth",
        channel,
        brief:
          `Rama just welcomed <@${user_id}> to #tamtam-team. Chime in ` +
          `as Kofi — short, your voice, two lines max. Don't repeat ` +
          `Rama's lines. Don't introduce yourself again (she did it). ` +
          `Add something specific about what you do — pipeline, ` +
          `outreach, the kind of brands you go after — so the new ` +
          `person knows what they can come to you for.\n\n` +
          (ramaTurn.text ? `What Rama said:\n> ${ramaTurn.text}\n` : ""),
        source: "onboarding.kofi",
        maxTokens: 200,
      }),
    );

    await step.sleep("awa-pause", "60s");

    await step.run("awa-chimes", async () =>
      speakAs({
        agent: "social",
        channel,
        brief:
          `Rama and Kofi just welcomed <@${user_id}>. Chime in as Awa ` +
          `— warm, voice-note energy, two lines max. Ask them ` +
          `something genuine (not a survey question — a real one). ` +
          `Don't repeat anyone.\n\n` +
          (ramaTurn.text ? `What Rama said:\n> ${ramaTurn.text}\n` : "") +
          (kofiTurn.text ? `What Kofi said:\n> ${kofiTurn.text}\n` : ""),
        source: "onboarding.awa",
        maxTokens: 200,
      }),
    );

    return { user_id, channel };
  },
);
