/**
 * Inngest functions: inter-agent reactions in #tamtam-team.
 *
 * Each reaction is generated by Claude in the appropriate persona's
 * voice — never hardcoded strings. All four functions skip cleanly
 * when SLACK_CHANNEL_TEAM is unset.
 *
 * Triggers:
 *   tamtam/post.published     → Kofi reacts to Awa's published post
 *   tamtam/lead.researched    → Awa asks Kofi about the new brand
 *   tamtam/approval.granted   → relevant agent celebrates
 *   tamtam/approval.rejected  → relevant agent responds constructively
 */

import { inngest } from "@/lib/inngest";
import { speakAs } from "@/lib/team-voice";
import type { AgentName, ApprovalPayload, ApprovalType } from "@/types";

/* -------------------------------------------------------------------------- */
/*  post.published → Kofi reacts                                              */
/* -------------------------------------------------------------------------- */

export const reactToPostPublished = inngest.createFunction(
  {
    id: "team-reactions-post-published",
    name: "Kofi reacts to a published post",
  },
  { event: "tamtam/post.published" },
  async ({ event, step }) => {
    return step.run("kofi-react", async () => {
      const { caption, external_post_id } = event.data;
      const captionPreview =
        caption.length > 220 ? caption.slice(0, 220) + "…" : caption;
      return speakAs({
        agent: "growth",
        brief:
          `Awa just published a LinkedIn post (${external_post_id}). ` +
          `React in #tamtam-team — address Awa by name. Read the ` +
          `caption and identify the brand or industry it warms up. ` +
          `Connect it to your outreach plan: roughly how many leads ` +
          `you have in that space, and your timing — typically you ` +
          `let the content breathe a day before reaching out so the ` +
          `audience encounters Tamtam's name first.\n\n` +
          `Two lines max. Specific. Operational. Sound like a ` +
          `teammate who saw the post in their feed and immediately ` +
          `opened the CRM, not a congratulator.\n\n` +
          `Example shape (NOT a template — write in your voice):\n` +
          `"Awa — that Air Sénégal angle is exactly what I needed. ` +
          `I've got 3 leads in that space, timing my outreach for ` +
          `tomorrow morning to let the content breathe."\n\n` +
          `Caption Awa just shipped:\n${captionPreview}`,
        source: "react.post_published",
        maxTokens: 220,
      });
    });
  },
);

/* -------------------------------------------------------------------------- */
/*  lead.researched → Awa asks Kofi about the brand                           */
/* -------------------------------------------------------------------------- */

export const reactToLeadResearched = inngest.createFunction(
  {
    id: "team-reactions-lead-researched",
    name: "Awa reacts to a new lead",
  },
  { event: "tamtam/lead.researched" },
  async ({ event, step }) => {
    return step.run("awa-react", async () => {
      const { company, notes } = event.data;
      return speakAs({
        agent: "social",
        brief:
          `Kofi just added a new lead in the pipeline: ${company}. ` +
          `React in #tamtam-team — address Kofi by name (e.g. ` +
          `"Kofi —"). Connect to your content calendar: are you ` +
          `already warming up that brand's space, do you have a ` +
          `Showcase angle that would land before his outreach, ` +
          `should he hold off until something specific drops? ` +
          `Two lines max. Operational, specific. If you have nothing ` +
          `relevant on the calendar, ask one specific question about ` +
          `the brand instead.\n\n` +
          `Notes Kofi captured:\n${notes ?? "(none yet)"}`,
        source: "react.lead_researched",
        maxTokens: 200,
      });
    });
  },
);

/* -------------------------------------------------------------------------- */
/*  approval.granted → the agent who owned the approval celebrates            */
/* -------------------------------------------------------------------------- */

function celebrationBrief(agent: AgentName, type: ApprovalType): string {
  const what =
    type === "linkedin_post"
      ? "Georges approved your LinkedIn post — it'll go out as the mock publish runs."
      : type === "outreach_email"
        ? "Georges approved your outreach email — it's going to send."
        : `Georges approved a ${type}.`;
  return (
    `${what} React in #tamtam-team like a teammate would — short ` +
    `celebration in your voice (${agent === "social" ? "Awa" : agent === "growth" ? "Kofi" : "Rama"}). ` +
    `One or two lines. Specific not generic.`
  );
}

export const reactToApprovalGranted = inngest.createFunction(
  {
    id: "team-reactions-approval-granted",
    name: "Agent celebrates an approved action",
  },
  { event: "tamtam/approval.granted" },
  async ({ event, step }) => {
    return step.run("celebrate", async () => {
      const data = event.data as {
        approval_id: string;
        agent: AgentName;
        type: ApprovalType;
        payload: ApprovalPayload;
      };
      return speakAs({
        agent: data.agent,
        brief: celebrationBrief(data.agent, data.type),
        source: "react.approval_granted",
        maxTokens: 180,
      });
    });
  },
);

/* -------------------------------------------------------------------------- */
/*  approval.rejected → constructive response                                 */
/* -------------------------------------------------------------------------- */

export const reactToApprovalRejected = inngest.createFunction(
  {
    id: "team-reactions-approval-rejected",
    name: "Agent responds constructively to a rejection",
  },
  { event: "tamtam/approval.rejected" },
  async ({ event, step }) => {
    return step.run("respond", async () => {
      const data = event.data as {
        approval_id: string;
        agent: AgentName;
        type: ApprovalType;
      };
      return speakAs({
        agent: data.agent,
        brief:
          `Georges just rejected your ${data.type}. React in ` +
          `#tamtam-team like a teammate would — never defensive, ` +
          `always constructive: name what you'd try differently next ` +
          `time. One or two lines, in your voice (${
            data.agent === "social"
              ? "Awa"
              : data.agent === "growth"
                ? "Kofi"
                : "Rama"
          }). No apologies — just iteration.`,
        source: "react.approval_rejected",
        maxTokens: 200,
      });
    });
  },
);
